# Define the exports for the prx
PSP_BEGIN_EXPORTS

# These four lines are mandatory (although you can add other functions like module_stop)
# syslib is a psynonym for the single mandatory export.
PSP_EXPORT_START(syslib, 0, 0x8000)
PSP_EXPORT_FUNC_HASH(module_start)
PSP_EXPORT_VAR_HASH(module_info)
PSP_EXPORT_END

PSP_EXPORT_START(sceIdMgr_driver, 0x0011, 0x0001)
PSP_EXPORT_FUNC_NID(sceIdMgr_driver_F464F91C, 0xF464F91C)
PSP_EXPORT_END

PSP_END_EXPORTS
